# Generated by Django 3.1.1 on 2021-07-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=True, max_length=100)),
                ('description', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='about/')),
            ],
        ),
    ]
